providers = ["php", "node"]

[phases.setup]
aptPkgs = ["git", "unzip"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader --no-interaction"]

[phases.build]
cmds = [
    "php artisan config:clear",
    "php artisan storage:link || true"
]

[start]
cmd = "php artisan migrate --force --no-interaction && php artisan db:seed --force --no-interaction && php artisan serve --host=0.0.0.0 --port=$PORT"
